### PR TITLE
CICD pipeline

### PR DESCRIPTION
**Pull request by Sealaholic**
CICD pipeline for syntax and credentials check.

### CODE REVIEW

**Review by chengchiehhung — CHANGES_REQUESTED** [review]
Please add the report contents to the comments area on the PR.

**Comment by Sealaholic** [comment]
***CCS passed***

**Comment by Sealaholic** [comment]
***CCS passed***

**Comment by Sealaholic** [comment]
***Pylint check passed***

**Comment by Sealaholic** [comment]
***Pylint check passed***

**Comment by Sealaholic** [comment]
***Pylint check passed***

**Pull request closed without merging**
